// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANC-RnkSUFtOyiPZDdaJgxDkPIwPjqsvY',
    appId: '1:1084586462925:web:b801184f2b26045884a384',
    messagingSenderId: '1084586462925',
    projectId: 'my-personal-project-7b26c',
    authDomain: 'my-personal-project-7b26c.firebaseapp.com',
    storageBucket: 'my-personal-project-7b26c.appspot.com',
    measurementId: 'G-MZGHSBKFEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0TFHJPrmP6lLifuV5kD3jD-ZbUIrX3zI',
    appId: '1:1084586462925:android:5cf7295623e2926f84a384',
    messagingSenderId: '1084586462925',
    projectId: 'my-personal-project-7b26c',
    storageBucket: 'my-personal-project-7b26c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD84z4XAk2jIk_QpeQtiaGWzq3_x0gJ3mc',
    appId: '1:1084586462925:ios:0b80d66afebb8bd684a384',
    messagingSenderId: '1084586462925',
    projectId: 'my-personal-project-7b26c',
    storageBucket: 'my-personal-project-7b26c.appspot.com',
    iosBundleId: 'com.example.myPersonalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD84z4XAk2jIk_QpeQtiaGWzq3_x0gJ3mc',
    appId: '1:1084586462925:ios:0b80d66afebb8bd684a384',
    messagingSenderId: '1084586462925',
    projectId: 'my-personal-project-7b26c',
    storageBucket: 'my-personal-project-7b26c.appspot.com',
    iosBundleId: 'com.example.myPersonalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANC-RnkSUFtOyiPZDdaJgxDkPIwPjqsvY',
    appId: '1:1084586462925:web:90460cc62e5930a884a384',
    messagingSenderId: '1084586462925',
    projectId: 'my-personal-project-7b26c',
    authDomain: 'my-personal-project-7b26c.firebaseapp.com',
    storageBucket: 'my-personal-project-7b26c.appspot.com',
    measurementId: 'G-S70Y90T2EH',
  );
}
